# don't insert blank lines between prompts
add_newline = false

[python]
# see: https://starship.rs/config/#python
# Configures the python binaries that Starship should execute when getting the ${version}.
python_binary = ['python', 'python3']
