#!/usr/bin/env bash

# Get the IP address of the current machine --
ip="$( ifconfig | grep -Ew inet | cut -f 2 -d " " | tail -n 1 )"

# Get the username of the current user
host="$( whoami )"

echo "$host@$ip"

