name: ShellCheck

on:
  push:
    branches:
      - '*'

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        env:
          # force check zshrc, which is checked by default
          SHELLCHECK_OPTS: --shell=bash
        with:
          format: tty
